// Director feature exports
export * from './pages/DirectorDashboard';
export * from './pages/DirectorReports';
export * from './pages/StockManagement';
export * from './pages/StoreManagement';
export * from './pages/ProductCatalog';
export * from './pages/EmployeeManagement';
export * from './pages/SalesValidation';
export * from './pages/TransfertManagement';
export * from './pages/InventaireManagement';
export * from './pages/TraceabilityManagement';
export * from './pages/SimpleTransfertManagement';
export * from './pages/SimpleInventaireManagement';
export * from './pages/SimpleTraceabilityManagement';